In [45]:
import numpy as np
from PIL import Image

In [6]:
it = [3,6,7,11]

In [8]:
n = np.array(it)

In [9]:
type(n) 

numpy.ndarray

In [12]:
d  = {"app":"A red", "mango":"King"}

In [13]:
np.array(d)

array({'app': 'A red', 'mango': 'King'}, dtype=object)

In [26]:
twod = np.array([[1,2],[4,5]])

twod
twod.shape
twod.size
twod.itemsize


4

In [20]:
y = np.array([2,5,6,"77"])

In [21]:
y

array(['2', '5', '6', '77'], dtype='<U11')

In [22]:
n

array([ 3,  6,  7, 11])

In [29]:
list(range(9,15))

[9, 10, 11, 12, 13, 14]

In [30]:
np.arange(7,12,2)

array([ 7,  9, 11])

In [31]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distan

In [39]:
ar1 = np.arange(40)

In [40]:
ar2 = ar1.reshape(8,5)


In [41]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [42]:
ar1[0] = 1000

In [43]:
ar2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [44]:
ar1 is ar2

False