In [3]:
a = 6

In [4]:
a = 8

In [5]:
a

8

In [6]:
a

8

In [7]:
import numpy as np

In [8]:
it  = [2,6,7,8,9]

In [9]:
n = np.array(it)

In [10]:
n

array([2, 6, 7, 8, 9])

In [11]:
type(n)

numpy.ndarray

In [12]:
d = {"apple" : "A sweet red fruit", "mango" :"King of fruits"}

In [13]:
d

{'apple': 'A sweet red fruit', 'mango': 'King of fruits'}

In [14]:
twod = np.array([[1,2] , [3,4,5]])

twod

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [15]:
  y = np.array([2,5,5,"77"])

In [16]:
y

array(['2', '5', '5', '77'], dtype='<U11')

In [17]:
list(range(10,19,3))

[10, 13, 16]

In [20]:
np.arange(7,12,2)

array([ 7,  9, 11])

In [27]:
np.arange(40).reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [28]:
arr1 = np.arange(40)

In [30]:
arr2 = arr1.reshape(8,5)

In [31]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [32]:
arr1[0]=1000

In [33]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [34]:
arr1 is arr2

False