In [21]:
import numpy as np

In [28]:
list = [1,2]
ar = np.array(list)

In [29]:
type(ar)

numpy.ndarray

In [30]:
print(ar)

[1 2]


In [31]:
ar.shape

(2,)

In [35]:
type(ar)

numpy.ndarray

In [47]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,3,14,15]
arr = np.array([list1 , list2, list3])

In [48]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15]])

In [49]:
arr.shape

(3, 5)

In [52]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 3, 14, 15]])

In [42]:
arr  = np.array([1,2,3,4,5,6,7,8,9])

In [43]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[3]

4

In [55]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,3,14,15]
arr = np.array([list1 , list2, list3])

In [56]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15]])

In [57]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15]])

In [58]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  3, 14, 15]])

In [60]:
arr[:2,:2]

array([[1, 2],
       [6, 7]])

In [62]:
arr[1:3,2:4]

array([[ 8,  9],
       [ 3, 14]])

In [63]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [69]:
arr = np.arange(0,10,step = 2)

In [70]:
print(arr)

[0 2 4 6 8]


In [71]:
arr

array([0, 2, 4, 6, 8])

In [72]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [74]:
#copy function and broadcasting

arr[3:]=100

In [75]:
arr

array([  0,   2,   4, 100, 100])

In [76]:
arr1 = arr

In [78]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [80]:
arr1 = arr.copy()
print(arr)
arr1[3:] = 1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [85]:
val  =2
arr[arr<300]

array([0, 2, 4])

In [88]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
np.ones(4)

array([1., 1., 1., 1.])

In [90]:
np.ones(4 , dtype = int)

array([1, 1, 1, 1])

In [92]:
np.ones((2,5) , dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
np.random.rand(3,3)

array([[0.65821302, 0.88188016, 0.67620287],
       [0.76392828, 0.71195164, 0.50680126],
       [0.34966657, 0.50577622, 0.04595815]])

In [96]:
arr_ex = np.random.randn(4,4) #std normal distribution

In [97]:
arr_ex

array([[ 0.84113886,  0.00950806, -0.29274679, -0.13122636],
       [ 2.27489381, -1.74584543,  1.04933039,  0.45819304],
       [ 0.37545394, -0.7879794 ,  0.50489793,  0.57980773],
       [ 0.63644947, -0.17872541,  0.39429298, -0.38933195]])

In [99]:
np.random.randint(0,100,8).reshape(2,4)

array([[88, 54, 95, 26],
       [12, 45, 63, 96]])

In [100]:
np.random.random_sample((1,5))

array([[0.26134161, 0.63626512, 0.45949765, 0.69077701, 0.12873081]])